# Site settings
#look at site
url: "http://ivyracquel.github.io"
title: "{ Racquel Ivy Awuor }"
description: "Blog and website of Ivy Awuor"
keywords: "racquel, awuor, ivy, ivyracquel, technology, computer science, electrical engineering, research, AHA, ultrasound, programming"
#keywords:"racquel, awuor, ivy, rawuor, technology, computer science, electrical engineering, computer engineering, research, programming"
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
google-tracking-id: "UA-35880426-3"
#google-tracking-id:false
disqus-shortname: "rawuor"

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  #Blog: 'blog'
  #Research:'research'
  Career: 'career'
 #Projects: 'projects'
  Contact: 'contact'

#background-img: "/img/intro-bg.jpg"
background-img: "/img/intro-bg1.jpg"

# About variables

me-img: "/img/me1.jpg"

# Blog variables
paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: True
twitter-share: True
reddit-share: False

# Career variables

events:
  - image: "/img/career/uwm.png"
    date:  "January 2015 - Today"
    description: "Software development intern"
  - image: "/img/career/uwm.png"
    date: "July 2015 - Today"
    description: "Summer Research Assistant @<a href = \"http://uwm.edu/engineering/academics-2/departments/electrical-engineering\" target = \"_blank\">University of Wisconsin-Milwaukee Department of Electrical Engineering and Computer Science </a> "
  - image: "/img/career/uoa.jpg"
    date: "May 2015"
    description: "Graduated: Completed BSc in Electrical and Computer Engineering from the <a href = \"http://rochester.edu\"> University of Rochester </a>"
  - image: "/img/career/AHA.jpg"
    date: "May 2014 - August 2014"
    description: "American Heart Association Research Fellow. Designed and implemented imaging algorithms for cardiovascular ultrasound imaging."
  - image: "/img/career/uofr.png"
    date: "May 2013 - August 2014"
    description: "Undergraduate research assistant @<a href =\"http://www.ece.rochester.edu/projects/doyley_lab\" target = \"_blank\"> Parametric Imaging Research Lab</a> at the University of Rochester. Focus on algorithm design and implementation for ultrasound imaging."
  - image: "/img/career/uoa.jpg"
    date: "August 2011 - May 2013"
    description: "Undergraduate studies @ <a href=\"http://www.ece.rochester.edu\" target=\"_blank\">Department of Electrical and Computer Engineering </a> in University of Rochester (Freshman-Sophomore year)"

# First image of the Career timeline
career-img: "/img/career/default.jpg"

#projects variables  
projects:
  - title: "Flappy bird clone"
    description: "Used XCode and SpriteKit to create a clone of the Flappy bird game for iOS.Code on github: <a href = \"https://github.com/rawuor\" target =\"_blank\">Here!</a> Programming language: Objective C"
    
  #-title: "Stereo input filter"
  #  description: "Implemented a filter for stereo audio input using XCode and Faust. Code on github: <a href = \"https://github.com/rawuor\" target = \"_blank\" >Here!</a> Programming language: Faust"
    
  #-title: "Guitar Tuner app"
  #  description: "An guitar tuner app, adapted from . Code on github:<a href = \"https://github.com/rawuor\" target = \"_blank\">Here</a>"
# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "rss"
    url: "/feed.xml"
  - title: "github"
    url: "https://github.com/rawuor"
  - title: "linkedin"
    #url: "http://no.linkedin.com/in/PanosSakkos"
    url: "https://www.linkedin.com/pub/ivy-awuor/5a/3ba/2ab"
  - title: "facebook"
    url: "https://www.facebook.com/iracquel1"
    #url:"https://www.youtube.com/channel/UCO7m8lbIOD2aAm5z3hS8l7g"
  - title: "quora"
    #url: "https://soundcloud.com/psakkos/"
    url: "https://www.quora.com/Ivy-Racquel"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
